### ISSUE TITLE
Require python >=3.5.3

### ISSUE THREAD

**Issue by Callek** [mozilla-releng/addonscript#33]
So, with the requirements bump of yarl, we now require at least python 3.5.3, this can be reverted but isn't a big deal atm. Since our deployment will soon use 3.6.x but means I can't bump pinned versions from here to make our deployment match up just yet.

**Comment by Callek** [comment]
@escapewindow can you please comment here (or ping me) once we deploy py3.6 for addonscript's deployment?

**Comment by escapewindow** [comment]
We have deployed py36.

**Comment by escapewindow** [comment]
Let's close this :)
